name: Sync README.md

on:
  push:
    paths:
      - 'README.md'
      - 'CGH_HomeWork/README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync README.md
      run: |
        # 루트 디렉토리의 README.md 파일을 CGH_HomeWork 폴더로 복사
        cp README.md CGH_HomeWork/README.md
        
        # CGH_HomeWork 폴더의 README.md 파일을 루트 디렉토리로 복사  
        cp CGH_HomeWork/README.md .
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Sync README.md" || echo "No changes to commit"
        git push || echo "No changes to push"
